#
#Sun Mar 01 02:07:18 UTC 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, --headless\=chrome, --no-sandbox, --disable-dev-shm-usage, --window-size\=1920,1080, --ignore-certificate-errors, --remote-allow-origins\=*, --headless], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
