serenity.project.name=Test Automation JM Consultant

# Indicar que vamos a usar un WebDriver remoto
webdriver.driver = remote

# URL del hub de BrowserStack con tus credenciales
webdriver.remote.url = https://nicolascastro_TiIwe8:7ByLHMTEgunqaHqVXtDA@hub-cloud.browserstack.com/wd/hub

# Navegador y versión que quieres usar
capabilities.browserName = Chrome
capabilities.browserVersion = 115.0

# Sistema operativo
capabilities.os = Windows
capabilities.osVersion = 11

# Opciones adicionales de BrowserStack
capabilities['bstack:options'] = {
"projectName": "MiProyectoSerenity",
"buildName": "Build-1",
"sessionName": "Login Test"
}