name: CI/CD - Serenity BDD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar JDK 17 con cache Maven
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Ejecutar pruebas y generar reporte Serenity
        run: |
          mvn clean verify serenity:aggregate -B -Dheadless.mode=true

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: serenity-reports
          path: target/site/serenity

      - name: Publicar en GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/serenity
          publish_branch: gh-pages

      - name: Mostrar URL del reporte en el log
        if: github.ref == 'refs/heads/main'
        run: |
          echo "🚀 Serenity Report disponible en:"
          echo "https://kevinicolasvasquezcastro.github.io/PruebaAutoDavivienda/"