name: CI/CD - Serenity BDD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: https://kevinicolasvasquezcastro.github.io/PruebaAutoDavivienda/

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Build and run tests
        run: mvn clean verify serenity:aggregate -B -Dheadless.mode=true

      - name: Upload Serenity Reports
        uses: actions/upload-artifact@v4
        with:
          name: serenity-reports
          path: target/site/serenity

      - name: Deploy Serenity Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/serenity
          publish_branch: gh-pages

      - name: Show GitHub Pages URL
        run:
          echo "Reporte disponible en: https://kevinicolasvasquezcastro.github.io/PruebaAutoDavivienda/"